### ISSUE TITLE
wrong version information (still displaying the old version number)

### ISSUE THREAD

**Issue by imm0r** [d2k2-git/D3Helper.Public#10]
Hey d2k2,

just wanted to let you know that, it seems like you've missed updating the version information for the latest dD3H version (v17.04.18.0) it is still displaying v17.03.24.0.
Don't get me wrong, basically, this is not a problem at all, I just struggled to figure out if I accidently downloaded the wrong file or if the version information wasn't updated ^^

 ![d3hlatestissue](https://cloud.githubusercontent.com/assets/7317860/25635766/93889f66-2f7f-11e7-8457-7d3b5c26480f.jpg)

**Thanks for keeping D3H alive! You're doing a very good job!**

**Comment by d2k2-git** [comment]
updated version number
