### ISSUE TITLE
Horrify Condition arent working correctly

### ISSUE THREAD

**Issue by DaLeberkasPepi** [d2k2-git/D3Helper.Public#12]
All Conditions for the Witchdoctor Skill Horrify dont work correctly. When there are a lot of mobs around it stops working

**Comment by d2k2-git** [comment]
its a simple cooldown skill. there is no special code for "horrify" skill. please use the forum for questions how to setup conditions. it will help when you export your condition definitions, so others can check and help.

**Comment by DaLeberkasPepi** [comment]
no even if i set it on cast when skill is not on cooldown it doesnt work thats why i post it as a bug

**Comment by d2k2-git** [comment]
i tested it quickly with "player_skill_isnotoncooldown". i can not reproduce this bug.

**Comment by DaLeberkasPepi** [comment]
yeah thats why i said you have to get about 20 mobs around you then it stops working for some reason

**Comment by d2k2-git** [comment]
tested with +40mobs

**Comment by DaLeberkasPepi** [comment]
i can send you a video with it not working after i blacked the important parts out

**Comment by DaLeberkasPepi** [comment]
Updated previous post with more information

**Comment by d2k2-git** [comment]
did you try to disable all other skills for casting? they have red border when disabled.

**Comment by DaLeberkasPepi** [comment]
with the other definitions deactivated it seems like its working fine. But this only makes it stranger

**Comment by DaLeberkasPepi** [comment]
on further testing it seems like it has something to do with the soulharvest definition.

Definition
[{"ConditionGroup":6,"Type":45,"Values":[67616.0],"ValueNames":[0],"comment":null,"enabled":true,"version":0,"DisplayText":"Player_Power_IsNotOnCooldown => [PowerSNO:Witchdoctor_SoulHarvest]"},{"ConditionGroup":6,"Type":5,"Values":[18.0,5.0,1.0],"ValueNames":[1,2,3],"comment":null,"enabled":true,"version":0,"DisplayText":"World_MonstersInRange => [Distance:18 / Value:5 / Bool:1]"},{"ConditionGroup":7,"Type":45,"Values":[67616.0],"ValueNames":[0],"comment":null,"enabled":true,"version":0,"DisplayText":"Player_Power_IsNotOnCooldown => [PowerSNO:Witchdoctor_SoulHarvest]"},{"ConditionGroup":7,"Type":7,"Values":[18.0,1.0,1.0],"ValueNames":[1,2,3],"comment":null,"enabled":true,"version":0,"DisplayText":"World_BossInRange => [Distance:18 / Value:1 / Bool:1]"},{"ConditionGroup":8,"Type":2,"Values":[67616.0,749.0],"ValueNames":[0,4],"comment":null,"enabled":true,"version":250,"DisplayText":"Player_IsBuffNotActive => [PowerSNO:Witchdoctor_SoulHarvest / AttribID:749]"},{"ConditionGroup":7,"Type":2,"Values":[430674.0,759.0],"ValueNames":[0,4],"comment":null,"enabled":true,"version":250,"DisplayText":"Player_IsBuffNotActive => [PowerSNO:P2_ItemPassive_Unique_Ring_038 / AttribID:759]"},{"ConditionGroup":6,"Type":2,"Values":[430674.0,759.0],"ValueNames":[0,4],"comment":null,"enabled":true,"version":250,"DisplayText":"Player_IsBuffNotActive => [PowerSNO:P2_ItemPassive_Unique_Ring_038 / AttribID:759]"},{"ConditionGroup":7,"Type":2,"Values":[430674.0,760.0],"ValueNames":[0,4],"comment":null,"enabled":true,"version":250,"DisplayText":"Player_IsBuffNotActive => [PowerSNO:P2_ItemPassive_Unique_Ring_038 / AttribID:760]"},{"ConditionGroup":6,"Type":2,"Values":[430674.0,760.0],"ValueNames":[0,4],"comment":null,"enabled":true,"version":250,"DisplayText":"Player_IsBuffNotActive => [PowerSNO:P2_ItemPassive_Unique_Ring_038 / AttribID:760]"},{"ConditionGroup":8,"Type":5,"Values":[18.0,5.0,1.0],"ValueNames":[1,2,3],"comment":null,"enabled":true,"version":250,"DisplayText":"World_MonstersInRange => [Distance:18 / Value:5 / Bool:1]"},{"ConditionGroup":8,"Type":19,"Values":[67616.0,757.0,10.0],"ValueNames":[0,4,2],"comment":"","enabled":true,"version":250,"DisplayText":"Player_IsNotBuffCount => [PowerSNO:Witchdoctor_SoulHarvest / AttribID:757 / Value:10]"},{"ConditionGroup":6,"Type":76,"Values":[300.0],"ValueNames":[2],"comment":"","enabled":true,"version":250,"DisplayText":"Add_Property_TimedUse => [Value:300]"}]

**Comment by DaLeberkasPepi** [comment]
it also seems strange that only on the soulharvest definition the conditiongroup starts alread at 6
![image](https://cloud.githubusercontent.com/assets/1573408/26080605/a8fe0fdc-39c7-11e7-9448-77c887bf3355.png)

**Comment by DaLeberkasPepi** [comment]
i reduced the amount of conditiongrps and now it seems like its working like it should

**Comment by d2k2-git** [comment]
can not reproduce it. must be another bug. has nothing to do with horrirfy skill. maybe i would need your whole "definitions" folder to find it. as long as i can not reproduce it, i can not fix it.

**Comment by DaLeberkasPepi** [comment]
Did you download the definitions.zip in my previous post? There you can find all 3 definitions I used in the video

**Comment by d2k2-git** [comment]
Yes i did. Can not reproduce it.

**Comment by DaLeberkasPepi** [comment]
with every of them enabled? Maybe also the missing coe. The soul harvest conditions had a few references to the coe powersno. And with lon wd you cant run with coe. Could this produce this problem.
