### ISSUE TITLE
Latest D3 patch broke D3H again :(

### ISSUE THREAD

**Issue by imm0r** [d2k2-git/D3Helper.Public#15]
Hey d2k2,

hope you can help us out once again! Since the latest D3 patch (v2.6.0.46494) (60mb) D3Helper is no longer working.
I wasn't able to find any official changelog so I am instead just linking **_[D3Diff](http://ptr.d3planner.com/diff/powers/46006/46494)_** from D3Planner...

I can be wrong, but it looks like many changed offsets have shifted backward by 10bytes?!
@Enigma32 is already working on updating his **_[library](https://github.com/Enigma32/Enigma.D3)_**.

Thanks in advance for all your awesome work!

**Comment by d2k2-git** [comment]
d3helper does not require update for patch 2.6.0.46494. The enigma framework libraries must be updated. i will upload them later.

**Comment by imm0r** [comment]
yay thank you sir!
