### ISSUE TITLE
add player_iskeyforcemove

### ISSUE THREAD

**Issue by techdough** [d2k2-git/D3Helper.Public#2]
simliar to how we can check for keystandstill would be great to check for keyforcemove. this will make it much easier to turn on/off abilities while moving. false on keystandstill is not always equal to true on keyforcemove, for example standing still isn't keystandstill. so I don't think adding this property duplicates an existing feature.

**Comment by d2k2-git** [comment]
What about Player_IsMoving ?

**Comment by techdough** [comment]
player can be moving due to mouse click, which i would consider isn't the same as moving via force move key. 

On a side note another issue with player_ismoving is that there is often a 1 second delay between when you stop moving and when d3helper detects the movement stopped. I belive the code does a comparison of before and after coords. This can often mean death or dps loss because in higher GRs you are standing still for 1s. I tend not to use this as much because of that reason. If you want I can create a separate ticket on this.

Thanks for maintaining this. :)

**Comment by d2k2-git** [comment]
i just implemented a condtion "Key_ForceMove". but it only works if the key it doesnt work with mouse3 or mousewheel button. it works with other buttons.

**Comment by d2k2-git** [comment]
update: also able to read forcemove from mousekeys now. can not detect mousewheel.

**Comment by techdough** [comment]
excellent!!!!! thank you will take it for a spin.
