### ISSUE TITLE
Player_MaxPrimaryResource accounts for Resource Cost Reduction -- Shouldn't be?

### ISSUE THREAD

**Issue by donnydonovitz** [d2k2-git/D3Helper.Public#3]
Player_MaxPrimaryResource and Player_MaxSecondaryResource account for RCR, which should not be, IMO.

What I think is happening:

Player_MaxPrimaryResource = CurrentResource * (1 - RCR%)

**Comment by d2k2-git** [comment]
there is a forumla with fireReduce, but i dont understand the reason:

https://github.com/d2k2-git/D3Helper.Public/blob/master/D3Helper/A_Handler/SkillHandler/Aggregator_CastConditions.cs#L536-L554

**Comment by d2k2-git** [comment]
Many questions. But, i think the RCR should be removed in the formula. What you think?

**Comment by d2k2-git** [comment]
Even worse the calculation of the percentage value.

 A_Collection.Me.HeroDetails.ResourcePrimary_Percentage = (resourceNow / resourceTotal * 100) * resourcemultiplier;

ResourcePrimary_Percentage  can be higher than 100%. 

I think i should fix this

**Comment by d2k2-git** [comment]
instead the Resourcecostreduction (RCR) should be used in condition: Player_Skill_MinResource

**Comment by donnydonovitz** [comment]
IMO, MaxPrimaryResource should be used as is, without adding special formulas.

Good idea with MinResource, maybe add it in tooltip?

Thank you for your work, btw 👍 👍  👍

**Comment by d2k2-git** [comment]
Fixed with https://github.com/d2k2-git/D3Helper.Public/commit/b84eff5a599f9dcc97250674f56705517908c5fe
