### ISSUE TITLE
key_forcestandstill not working?

### ISSUE THREAD

**Issue by techdough** [d2k2-git/D3Helper.Public#4]
Create a condition Key_forcestandstill => bool:1 and attach it to punish (crusader) or other primary skills, which is on default mouse 1. Space bar is my forcestandstill key. 

move char, Press space and keep it pressed, character only uses punish once.
expected, character should keep using punish. 

This use to work with the regular version of d3helper, this is the first time I am trying your version.  seems whats going on is that it only fires on 1st keypress but not WHILE keyispressed as well. 

workaround: assign another skill to mouse 2 (blessed hammer) that you can spam, set the same cast conditions as mouse 1, now d3helper will alternate between mouse 1 and mouse 2.

**Comment by d2k2-git** [comment]
key_forcestandstill condition is working. maybe you made wrong configuration with other condition.

**Comment by d2k2-git** [comment]
closed
