### ISSUE TITLE
AutoCube UpgradeRare and ConvertMaterial

### ISSUE THREAD

**Issue by DaLeberkasPepi** [d2k2-git/D3Helper.Public#5]
AutoCube UpgradeRare / ConvertMaterial have to be updated as we all know for the new cube system introduced in Patch 2.5.

I also noticed that regarding the ConvertMaterial portion of d3helper it doesn't remember the setting you choose in Experimental => AutoCube ConvertMaterial.
If you choose a different setting than the default one and close after that the settings window and open it again the default value is set again
![2017-03-24 21_13_43-overlay](https://cloud.githubusercontent.com/assets/1573408/24312036/0fd1123c-10d7-11e7-98d4-c6816781282b.png)

**Comment by d2k2-git** [comment]
upgrade rare fixed with https://github.com/d2k2-git/D3Helper.Public/commit/b3b12e684ac5c955c9a45b0e3299d5cc5d2a3302
